services:
  backend:
    build: .
    image: online-wooden-backend:v2.0.0
    container_name: online-wooden-backend
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - /var/www/html/online-wooden/uploads:/app/uploads
    networks:
      - wooden-network
networks:
  wooden-network:
    driver: bridge
